describe('template spec', () => {
  it('open home screen add new todo', () => {
    cy.visit('http://localhost:5173/')
    cy.get('#signInEmail').type('sinem.alageyik@formsapp.com')
    cy.get('#signInPassword').type('123456')
    cy.get('#signInButton').click()

    cy.wait(1000)
    cy.get('#appHeader')
    cy.get('#profileSettings')
    cy.get('#todoicon')
    cy.get('#listoftodo')
    cy.get('#sort')
    cy.get('#plusCircle').click()
    cy.wait(500)
    cy.get('#addTodoTitle').type('Add new todo')
    cy.get('#addTodoDescription').type('Add new todo description')
    cy.get('#addTodoImage')
    cy.wait(500)
    cy.get('#addTodoButton').click()
    cy.wait(1000)
    cy.get('#todo').click()
    cy.wait(1000)
    cy.get('#backButton')
    cy.get('#clockButton')
    cy.get('#editButton')
    cy.get('#trashButton')
    cy.get('#detailTitle')
    cy.get('#detailDescription')
    cy.get('#detailImage')
    cy.get('#detailCreatedTime')
    cy.get('#editButton').click()
    cy.wait(1000)
    cy.get('#addTodoTitle').type('Title updated')
    cy.get('#addTodoDescription').type('Description updated')
    cy.wait(1000)
    cy.get('#addTodoButton').click()
    cy.wait(1000)
    cy.get('#todo').click()
    cy.get('#trashButton').click()
    cy.wait(1000)
    cy.get('#deleteTodo').click()
    cy.wait(1000)
  })

})