describe('template spec', () => {
  it('profile screen and log out', () => {
    cy.visit('http://localhost:5173/')
    cy.get('#signInEmail').type('sinem.alageyik@formsapp.com')
    cy.get('#signInPassword').type('123456')
    cy.get('#signInButton').click()
    cy.reload()
    cy.visit('http://localhost:5173/profile-screen')
    cy.get('#profileScreenHeaderTitle')
    cy.get('#profileScreenHeaderIcon')
    cy.get('#profileScreenIcon')
    cy.get('#userInfoContainer')
    cy.get('#userFullNameLabel')
    cy.get('#userFullName').should('have.text', 'Sinem Alageyik')
    cy.get('#userEmailLabel')
    cy.get('#userEmail').should('have.text', 'sinem.alageyik@formsapp.com')
    cy.get('#profileScreenLogoutRouter')
    cy.wait(1000)
    cy.get('#profileScreenLogout').click()
  })
})